# Generated by Django 6.0.4 on 2026-05-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('pickup_started', 'Pickup Started'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='created', max_length=30),
        ),
    ]
