# Generated by Django 6.0.4 on 2026-05-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('mini_truck', 'Mini Truck'), ('van', 'Van')], default='truck', max_length=20)),
                ('current_lat', models.FloatField()),
                ('current_lng', models.FloatField()),
                ('speed', models.FloatField(default=0)),
                ('fuel_level', models.IntegerField(default=100)),
                ('is_available', models.BooleanField(default=True)),
                ('driver_name', models.CharField(default='Unknown Driver', max_length=100)),
            ],
        ),
    ]
