# Generated by Django 6.0.4 on 2026-05-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_vehicle_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
