# Generated by Django 6.0.4 on 2026-05-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_vehicle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='capacity',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_name',
            field=models.CharField(default='Unknown Driver', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('truck', 'Truck'), ('mini_truck', 'Mini Truck'), ('van', 'Van')], default='truck', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_lng',
            field=models.FloatField(default=77.5946),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
