# Generated by Django 6.0.4 on 2026-05-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_remove_vehicle_capacity_vehicle_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='current_lat',
            field=models.FloatField(default=12.9716),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_lng',
            field=models.FloatField(default=77.5946),
        ),
    ]
