# Generated by Django 6.0.4 on 2026-05-07 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_alter_vehicle_id'),
        ('orders', '0013_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_vehicle', to='orders.order'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='route_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='route_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
