# Generated by Django 6.0.4 on 2026-05-12 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0022_alter_vehicle_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='active_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='avg_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='efficiency_score',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_consumed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='success_rate',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_distance',
            field=models.FloatField(default=0),
        ),
    ]
